---

- name: Copy k8s repository
  copy:
    src: "kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo
    follow: yes
    force: true

- name: Конфигурирование SELinux
  command:
    cmd: "{{ item }}"
  loop:
    - "setenforce 0"
    - "sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config"

- name: Отключаем swapoff -a 
  command:
    cmd: "{{ item }}"
  loop:
    - "swapoff -a"

- name: Отключаем swapoff
  lineinfile:
    path: /etc/fstab
    backup: yes
    state: absent
    regexp: ".*rhel-swap.*"

- name: yum install k8s
  yum:
    name: "{{ packages }}"
    allowerasing: "true"
    disable_gpg_check: "true"
    disable_excludes: 'kubernetes'
  vars:
    packages:
    - 'kubelet'
    - 'kubeadm'
    - 'kubectl'

- name: Добавляем аргументы в файл kubelet
  lineinfile:
    path: /etc/sysconfig/kubelet
    backup: yes
    line: "--runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice"
    insertafter: EOF

- name: Запуск K8s
  command:
    cmd: "systemctl enable --now kubelet"

- name: Добавляем правила iptables в файл k8s.conf
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    backup: yes
    create: yes
    insertafter: EOF
    line: "{{ item }}"
  loop:
    - "net.bridge.bridge-nf-call-ip6tables = 1"
    - "net.bridge.bridge-nf-call-iptables = 1"

- name: Применяем конфигурацию iptables
  command:
    cmd: "sysctl --system"

- name: Создание docker Daemon файла
  copy:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"
    force: true

- name: Ребут системы
  command:
    cmd: "{{ item }}"
  loop:
    - "mkdir -p /etc/systemd/system/docker.service.d"
    - "systemctl daemon-reload"
    - "systemctl restart docker"